name: Deploy Modulos to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Esto hará que se ejecute en tu notebook

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Backup, Deploy and Restart
        shell: wsl.exe {0}  # Usamos WSL para ejecutar los comandos
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          DATE=$(date +%Y%m%d_%H%M%S)
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@192.168.200.11 "
            if [ -d /home/gaesa/src/modulos ]; then
              mv /home/gaesa/src/modulos /home/gaesa/src/modulos_backup_\$DATE;
            fi
          "
          sshpass -p "$SSH_PASSWORD" rsync -avz --delete ./src/modulos/ root@192.168.200.11:/home/gaesa/src/modulos/
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@192.168.200.11 "docker restart gaesa"
