name: Deploy Modulos to Remote Servers

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cliente:
        description: 'Cliente específico a desplegar'
        required: true
        type: choice
        options:
          - gaesa
          - gaesademo

jobs:
  deploy-single:
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy using SSH
        shell: bash
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: root
          CLIENTE: ${{ github.event.inputs.cliente }}
        run: |
          if [ "$CLIENTE" = "gaesa" ]; then
            targetServer="192.168.102.7"
            targetPath="/var/www/appgaesa/src/modulos/"
            restartCommand="systemctl restart appgaesa"
          else
            targetServer="192.168.200.11"
            targetPath="/home/gaesa/src/modulos/$CLIENTE/"
            if [ "$CLIENTE" = "gaesademo" ]; then
              restartCommand="docker restart gaesa"
            else
              restartCommand="docker restart $CLIENTE"
            fi
          fi
          
          sshpass -p "$SSH_PASSWORD" rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --delete ./src/modulos/ "$SSH_USER@$targetServer:$targetPath" && \
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$targetServer" "$restartCommand"

  deploy-all:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    strategy:
      matrix:
        cliente: [
          'gaesa',
          'gaesademo'
        ]
      fail-fast: false
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy using SSH
        shell: bash
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: root
          CLIENTE: ${{ matrix.cliente }}
        run: |
          if [ "$CLIENTE" = "gaesa" ]; then
            targetServer="192.168.102.7"
            targetPath="/var/www/appgaesa/src/modulos/"
            restartCommand="systemctl restart appgaesa"
          else
            targetServer="192.168.200.11"
            targetPath="/home/gaesa/src/modulos/$CLIENTE/"
            if [ "$CLIENTE" = "gaesademo" ]; then
              restartCommand="docker restart gaesa"
            else
              restartCommand="docker restart $CLIENTE"
            fi
          fi
          
          sshpass -p "$SSH_PASSWORD" rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --delete ./src/modulos/ "$SSH_USER@$targetServer:$targetPath" && \
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$targetServer" "$restartCommand"