name: Deploy Modulos to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy using WSL
        shell: powershell
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          $env:SSHPASS = $env:SSH_PASSWORD
          wsl -e bash -c 'sshpass -p "'$SSHPASS'" rsync -avz --delete ./src/modulos/ root@192.168.200.11:/home/gaesa/src/modulos/ && sshpass -p "'$SSHPASS'" ssh -o StrictHostKeyChecking=no root@192.168.200.11 "docker restart gaesa"'